--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tanish/Pictures/837258.png"

-- Special
background="#2b2440"
foreground="#f6cab8"
cursor="#f6cab8"

-- Colors
color0="#2b2440"
color1="#FE5D78"
color2="#EC897E"
color3="#5B6089"
color4="#8C4F80"
color5="#359AA9"
color6="#11F3DC"
color7="#f6cab8"
color8="#ac8d80"
color9="#FE5D78"
color10="#EC897E"
color11="#5B6089"
color12="#8C4F80"
color13="#359AA9"
color14="#11F3DC"
color15="#f6cab8"
