# Shell variables
# Generated by 'wal'
wallpaper='/home/tanish/Pictures/Anime/2.jpg'

# Special
background='#0c0b19'
foreground='#ceaca6'
cursor='#ceaca6'

# Colors
color0='#0c0b19'
color1='#4E3355'
color2='#6B3B54'
color3='#4B3464'
color4='#704456'
color5='#DF683A'
color6='#994B4C'
color7='#ceaca6'
color8='#907874'
color9='#4E3355'
color10='#6B3B54'
color11='#4B3464'
color12='#704456'
color13='#DF683A'
color14='#994B4C'
color15='#ceaca6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
