--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tanish/Pictures/Anime/2.jpg"

-- Special
background="#0c0b19"
foreground="#ceaca6"
cursor="#ceaca6"

-- Colors
color0="#0c0b19"
color1="#4E3355"
color2="#6B3B54"
color3="#4B3464"
color4="#704456"
color5="#DF683A"
color6="#994B4C"
color7="#ceaca6"
color8="#907874"
color9="#4E3355"
color10="#6B3B54"
color11="#4B3464"
color12="#704456"
color13="#DF683A"
color14="#994B4C"
color15="#ceaca6"
